---
- hosts: docker
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
        
    - name: Upgrade installed packages
      apt:
        upgrade: dist

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install Node.js
      shell: |
        curl -sL https://deb.nodesource.com/setup_14.x | bash -
        apt-get install -y nodejs
        
    - name: Install Docker
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        apt-get update
        apt-get install -y docker-ce

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: marvsmpb/devops-reactjs:latest
        state: present

    - name: Start Docker container
      docker_container:
        name: devops-reactjs
        image: marvsmpb/devops-reactjs:latest
        ports:
          - "80:3000"
        state: started
